mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import settings

urlpatterns = patterns('',
    
    # main
    url(r'^$', 'mysite.main.views.home', name='home'),
    url(r'^about/$', 'mysite.main.views.about', name='about'),
    url(r'^contact/$', 'mysite.main.views.contact', name='contact'),
    url(r'^request/$', 'mysite.main.views.request_pass', name='request'),
    
    # login, logout ...
    url(r'^sign_up/$', 'mysite.main.views.signup', name='signup'),
    url(r'^sign_in/$', 'django.contrib.auth.views.login', {'template_name': 'templates/main/signin.html'}, name='signin'),
    url(r'^sign_out/$', 'django.contrib.auth.views.logout', {'next_page': '/sign_in/'}, name='signout'),
    
    # videos
    url(r'^search/$', 'mysite.video.views.search', name='search'),
    url(r'^upload/$', 'mysite.video.views.upload', name='upload'),
    url(r'^genres/$', 'mysite.video.views.genres', name='genres'),
    url(r'^genre/(?P<slug>[-\w]+)/$', 'mysite.video.views.genre', name='genre'),
    url(r'^hot/$', 'mysite.video.views.hot', name='hot'),
    url(r'^hot/(?P<by>[month|year|day]+)/$', 'mysite.video.views.hot', name='hot_by'),
    # using user-friendly url style avoiding network admin understanding of situation
    url(r'^v/(?P<video_id>\d+)$', 'mysite.video.views.watch', name='watch'),
    
    url( r'^videos/', include( 'videostream.urls' ) ),
    
    url(r'^assets/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    
    url(r'^admin/', include(admin.site.urls)),
)

mysite/mysite/video/models.py
# -*- coding: utf-8 -*-

from datetime import datetime
import sys

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from videostream.models import Video, VideoCategory
import mysite.video.utils as utils

def save_imdb_genres_from_data(data):
  genres = []
  if data.get('genres') is not None:
    for genre in data.get('genres'):
      try:
        vc = VideoCategory.objects.get(title=genre)
      except VideoCategory.DoesNotExist:
        vc = VideoCategory(title=genre, slug=slugify(genre)).save()
        del(vc)
        vc = VideoCategory.objects.get(title=genre)
      genres.append(vc)
    return genres
  return None
  

def save_imdb_data_for_video(video):
  data = utils.get_imdb_info_from_title(video.title)
  if data is None:
    return
  data = data[0]
  genres = save_imdb_genres_from_data(data)
  
  #print >>sys.stderr, '%s' % data
  info = VideoInfo(video=video, imdb_id=data.get('imdb_id'),
                   imdb_url=data.get('imdb_url'), year=data.get('year'),
                   poster=data.get('poster'), plot=data.get('plot'),
                   plot_short=data.get('plot_simple'))
  info.save()
  for genre in genres:
    video.categories.add(genre)


def update_imdb_data_for_video_from_imdb_id(video, _id):
  """
  Should only be called to update data not to create!
  """
  data = utils.get_imdb_info_from_id(_id)
  if data is None:
    return
  genres = save_imdb_genres_from_data(data)
  
  # Delete current info
  current_info = VideoInfo.objects.get(video=video)
  current_info.delete()
  
  # Create new info, because creating a new entry is faster to write
  # than to update each field one by one
  new_info = VideoInfo(video=video, imdb_id=data.get('imdb_id'),
                   imdb_url=data.get('imdb_url'), year=data.get('year'),
                   poster=data.get('poster'), plot=data.get('plot'),
                   plot_short=data.get('plot_simple'))
  new_info.save()


class VideoView(models.Model):
  """
  Simply a video view from a registered user
  """
  video = models.ForeignKey(Video)
  author = models.ForeignKey(User)
  
  created_date = models.DateTimeField(auto_now_add=True)
  # TODO:
  # In future we may want to store the ip address for geolocalisation and stats
  ip_address = models.GenericIPAddressField()
  
  def __unicode__(self):
    return '%s' % self.video.title


class VideoInfo(models.Model):
  """
  More information about the movie from IMDb
  """
  video = models.ForeignKey(Video)
  
  # information fields
  #actors
  #also_known_as = models.CharField(max_length=50, null=True, blank=True)
  #country = models.CharField(max_length=50, null=True, blank=True)
  poster = models.URLField(null=True, blank=True)
  plot = models.TextField(null=True, blank=True)
  plot_short = models.TextField(null=True, blank=True)
  
  imdb_id = models.CharField(max_length=50, null=True, blank=True)
  imdb_url = models.URLField()
  year = models.CharField(max_length=20, null=True, blank=True)
  
  
  created_date = models.DateTimeField(auto_now_add=True)
  
  def __unicode__(self):
    return 'info - %s' % self.video.title

mysite/mysite/video/views.py
# -*- coding: utf-8 -*-

#   Copyright (c) 2013, Thomas Gak Deluen. See
#   the COPYRIGHT file.

from datetime import datetime

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import redirect
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q, Count
from django.shortcuts import get_object_or_404

from annoying.decorators import render_to

from videostream.models import VideoCategory, Video
from mysite.video.models import VideoView, VideoInfo, save_imdb_data_for_video

@login_required
@csrf_protect
def search(request):
  # TODO: the whole thing 
  return HttpResponse('Yes you made it here !</br>It\'s not finished yet ')

@login_required
@csrf_protect
@render_to('templates/video/upload.html')
def upload(request):
  page = 'upload'
  title = _('Upload')
  
  # TODO: Do upload stuff
  
  return locals()

@login_required
@csrf_protect
def new(request):
  video = request.raw_post_data  # get raw uploaded video
  old_name = request.GET.get('qqfile', 'video_name')
  #name = "%s.jpg" % utilities.keygen(30)
  #url = '%s/uploads/%s' % (settings.MEDIA_ROOT, name)
    
  #	Writing video {
  #destination = open(url, 'wb+')
  #destination.write(image)
  #destination.close()
  #	}

  return HttpResponse('Video received correctly with filename=%s' % old_name)
  

@login_required
@csrf_protect
@render_to('templates/video/genres.html')
def genres(request):
  page = 'genres'
  title = _('Genres')
  
  genres = VideoCategory.objects.all().order_by('title')
  
  return locals()


@login_required
@csrf_protect
@render_to('templates/video/genre.html')
def genre(request, slug):
  page = 'genre'
  genre = get_object_or_404(VideoCategory, slug=slug)
  title = _('%s' % genre.title)
  
  # just get videos whose slug equals `slug`
  movies = Video.objects.filter(Q(categories__slug__exact=slug))
  
  return locals()


@login_required
@csrf_protect
@render_to('templates/video/hot.html')
def hot(request, by='all'):
  page = 'hot'
  title = _('Hot')
  
  # get date descriptors
  today = datetime.today()
  year = today.year
  month = today.month
  day = today.day
  
  # Here we check whether the user wants the hottest videos
  # of all the time, of this year, of this month or just of today
  
  if by == 'month':
    # get videos with greater number of views by month
    hot = Video.objects.annotate(num_views=Count('videoview'))\
                       .filter(videoview__created_date__month=month)\
                       .order_by('-num_views')[:20]
  elif by == 'year':
    # get videos with greater number of views by year
    hot = Video.objects.annotate(num_views=Count('videoview'))\
                       .filter(videoview__created_date__year=year)\
                       .order_by('-num_views')[:20]
  elif by == 'day':
    # get videos with greater number of views by day
    hot = Video.objects.annotate(num_views=Count('videoview'))\
                       .filter(videoview__created_date__day=day)\
                       .order_by('-num_views')[:20]
  else:
    # get videos with greater number of views all time
    hot = Video.objects.annotate(num_views=Count('videoview'))\
                       .order_by('-num_views')[:20]
  
  
  return locals()
  

@login_required
@csrf_protect
@render_to('templates/video/watch.html')
def watch(request, video_id):
  page = 'watch'
  video = get_object_or_404(Video, id=video_id)
  title = _('Watch: %s' % video.title)
  
  # Little hack to repeat action to check if info exists
  i = 0
  while 1:
    try:
      info = VideoInfo.objects.get(video=video)
      break
    except VideoInfo.DoesNotExist:
      save_imdb_data_for_video(video)
    if i == 1:
      info = None
      break
    i += 1
  
  # must be changed accordingly
  VideoView(video=video, author=request.user, ip_address="127.0.0.1").save()
  
  return locals()
  

mysite/templates/video/genre.html
{% extends 'templates/base.html' %}
{% load i18n %}

{% block content %}

<div class="content movies-container">
	<h2 class="content-subhead subhead-movie-margin">{{ genre.title }}</h2>
	
	<div class="pure-g-r" id="latest-movies">
	{% for movie in movies %}
	{% include 'templates/video/movie-el.html' %}
	{% empty %}
	<aside>
		<p>
		{% blocktrans %}
		There are no movies here
		{% endblocktrans %}
		</p>
	</aside>
	{% endfor %}
	</div>
	
</div>

{% endblock %}

mysite/templates/video/genres.html
{% extends 'templates/base.html' %}
{% load i18n %}

{% block content %}

<div class="content genres-container">
	<h2 class="content-subhead">{% trans 'Genres' %}</h2>
	
	<div class="pure-g-r" id="genres">
		{% for genre in genres %}
		<a href="{% url 'genre' slug=genre.slug %}" class="genre-el pure-u-1-4">
			{{ genre.title|upper }}
		</a>
		{% endfor %}
	</div>
	
</div>

{% endblock %}

mysite/templates/video/hot.html
{% extends 'templates/base.html' %}
{% load i18n %}

{% block content %}

<div class="content movies-container">
	<h2 class="content-subhead subhead-movie-margin">
		{% trans 'Movies of the moment' %}
		
		{% ifequal by 'all' %}
		{% trans 'of all time' %}
		{% endifequal %}
		
		{% ifequal by 'day' %}
		{% trans 'of today' %}
		{% endifequal %}
		
		{% ifequal by 'month' %}
		{% trans 'of this month' %}
		{% endifequal %}
		
		{% ifequal by 'year' %}
		{% trans 'of this year' %}
		{% endifequal %}
	</h2>
	<p class="subhead-movie-second subhead-movie-margin">
		{% trans 'By' %}
		
		<span class="link-list"><a href="{% url 'hot_by' by='day' %}">{% trans 'day' %}</a></span>
		<span class="link-list"><a href="{% url 'hot_by' by='month' %}">{% trans 'month' %}</a></span>
		<span class="link-list"><a href="{% url 'hot_by' by='year' %}">{% trans 'year' %}</a></span>
		
	</p>
	
	<div class="pure-g-r" id="latest-movies">
	{% for movie in hot %}
	{% include 'templates/video/movie-el.html' %}
	{% empty %}
	<aside>
		<p>
		{% blocktrans %}
		There are no movies here
		{% endblocktrans %}
		</p>
	</aside>
	{% endfor %}
	</div>
	
</div>

{% endblock %}

mysite/templates/video/movie-el.html
{% load i18n %}

<a href="{% url 'watch' video_id=movie.pk %}" class="movie-el pure-u-1-5">
	<img class="movie-poster" src="{% if movie.videoinfo_set.all.0.poster %}{{ movie.videoinfo_set.all.0.poster }}{% endif %}" />
	{% if not movie.videoinfo_set.all.0.poster %}
	<i class="icon-film poster-missing-icon"></i>
	{% endif %}
	<span class="movie-title">{{ movie.title }}</span>
	<!--<span class="movie-views">{{ movie.videoview_set.all|length }}</span>-->
</a>

mysite/templates/video/render_video.html
{% load i18n %}

{% comment %}{% load oembed_tags %}{% endcomment %}


{% if video_type == 'basicvideo' %}
		<div data-swf="{{ MEDIA_URL }}flowplayer/flowplayer.swf"
		class="flowplayer play-button"
		data-ratio="0.5625" data-embed="false" data-analytics="[Your analytics ID]">
			<video style="background: black;">
				{% for video in video_instance.basicvideo.html5video_set.all %}
				<source src="http://localhost:8888/videoapp{{ video.video_file.url }}" type="{{ video.get_video_type_display }}"/>
				{% endfor %}
				Your browser does not support the Video Tag.
			</video>

		</div>
{% endif %}


{% if video_type == 'flashvideo' %}

	<script type="text/javascript" src="{{ MEDIA_URL }}flowplayer/flash/flowplayer-3.2.12.min.js"></script>

    {% comment %}
        To use the flashplayer option, you need to have a flashplayer installed
        for your site. FlowPlayer is a good choice (http://flowplayer.org/).

        If you have a flashplayer installed, you need to customize this
        template and add the neccesarry HTML required for the flash
        player you chose.

        Here is a example, using flowplayer:

        <a href="{{ video_instance.flashvideo.flv_file.url }}"
            style="display: block; width={{ width }}; height={{ height }};"
            id="player"> </a>
    {% endcomment %}
		
		<a
				href="http://localhost:8888/videoapp{{ video_instance.flashvideo.flv_file.url }}"
				style="display: block; width: {{ width }}px; height: {{ height }}px;"
				id="player">
		</a>

    <!--<p>The player has been disabled in the demo app. See the template,
        <code>videostream/include/render_video.html</code>.

    <p>Just for reference, the flv file is: <code>{{ video_instance.flashvideo.flv_file.url }}</code>-->
		
		<script type="text/javascript">	
		flowplayer("player", "{{ MEDIA_URL }}flowplayer/flash/flowplayer-3.2.16.swf");
		</script>

{% endif %}

{% if video_type == 'embedvideo' %}

    {% comment %}
    
        If we have the video_code, then we use that to embed the video.
        If not then we will use django-oembed to display the video directly
        from the url.
        Make sure you have django-oembed installed.

    {% endcomment %}

    {% if video_instance.embedvideo.video_code %}
        {{ video_instance.embedvideo.video_code|safe }}
    {% else %}
        {% comment %}{% oembed %}{{ video_instance.embedvideo.video_url }}{% endoembed %}{% endcomment %}
				<pre>OEMBED is not installed, open file 'videoapp/mysite/templates/video/render_video.html'</pre>
    {% endif %}

{% endif %}

mysite/templates/video/upload.html
{% extends 'templates/base.html' %}
{% load i18n %}

{% block content %}

<script type="text/javascript" src="{{ MEDIA_URL }}js/fileuploader-custom.js"></script>

<div class="header pure-u-1">
	<h1 class="pure-u-1">{% trans 'Upload' %}</h1>
	<h2 class="pure-u">{% trans 'Upload a new movie' %}</h2>
</div>

<div class="content">
	<h2 class="content-subhead subhead-movie-margin">{% blocktrans %}
	{% endblocktrans %}
	</h2>
	
	<!-- uploader content -->
	
	<!-- uploader javascript -->
	<script type="text/javascript">
	</script>
	
</div>

{% endblock %}

mysite/templates/video/watch.html
{% extends 'templates/base.html' %}
{% load i18n %}
{% comment %}{% load oembed_tags %}{% endcomment %}
{% load videostream_tags %}

{% block extra_head %}
<link href="{{ MEDIA_URL }}flowplayer/skin/minimalist.css" rel="stylesheet">
<style>
/* custom player skin */
.flowplayer { /*width: 80%*/; background-color: black; background-size: cover; /*padding: 50px inherit;*/ /*max-width: 800px;*/ }
.flowplayer .fp-controls { background-color: rgba(0, 0, 0, 0.61)}
.flowplayer .fp-timeline { background-color: rgba(204, 204, 204, 1)}
.flowplayer .fp-progress { background-color: rgba(0, 167, 200, 1)}
.flowplayer .fp-buffer { background-color: rgba(249, 249, 249, 1)}
/*.flowplayer { background-image: url(http://farm5.staticflickr.com/4117/4870052004_c0997bcf8d_b.jpg)}*/
</style>
{% endblock %}

{% block content %}

<div class="content player-container">
	<h2 class="content-subhead subhead-movie-margin">{{ video.title }}</h2>
	
	<div class="pure-g-r" id="movie-player">
		
		<!-- Render video -->
		
			{% render_video video 800 600 %}
			
	</div>
	
	
	{% if info %}
	<div class="pure-g-r" id="movie-info">
		<ul>
			<li><b>{% trans 'Plot:' %}</b> {{ info.plot_short }}</li>
		</ul>
		
	</div>
	{% endif %}
	
</div>

<!-- flowplayer javascript -->
<script type="text/javascript" src="{{ MEDIA_URL }}flowplayer/flowplayer.min.js"></script>

{% endblock %}